# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals win-docker

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs:
    solution: $(solution)
    configuration: $(buildConfiguration)
    restoreNugetPackages: true
    msbuildLocationMethod: 'version'
    msbuildArguments: '/t:Rebuild /p:Configuration=Release /p:outdir=".\out\\"'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      # Define clear text string for username and password
      [string]$userName = 'jaroldan'
      [string]$userPassword = 'Rollingstones01'

      # Convert to SecureString
      [securestring]$secStringPassword = ConvertTo-SecureString $userPassword -AsPlainText -Force

      [pscredential]$credObject = New-Object System.Management.Automation.PSCredential ($userName, $secStringPassword)


      $LocalPath =  "C:\repos\samplecopy\"
      $RemotePath = "C:\repos\"

      $TargetSession = New-PSSession -ComputerName 10.0.0.5 -Credential $credObject
            
      Copy-Item -Path $LocalPath -Destination $RemotePath -ToSession $TargetSession -Force -Recurse


